const mongoose = require("mongoose");
require("dotenv").config();

const Product = require("./models/Product");

const products = [
  {
    name: "Rebar Coupler",
    category: "Couplers",
    hsn: "7308",
    gst: 18,
    rate: 40,
    stock: 5000,
    unit: "pcs",
  },
  {
    name: "Rebar Roll Tech Coupler",
    category: "Couplers",
    hsn: "7308",
    gst: 18,
    rate: 55,
    stock: 3000,
    unit: "pcs",
  },
  {
    name: "Parallel Rebar Roll Thread Coupler",
    category: "Couplers",
    hsn: "7308",
    gst: 18,
    rate: 60,
    stock: 2500,
    unit: "pcs",
  },
  {
    name: "MBT Coupler",
    category: "Couplers",
    hsn: "7308",
    gst: 18,
    rate: 180,
    stock: 1000,
    unit: "pcs",
  },
  {
    name: "Grout Coupler",
    category: "Couplers",
    hsn: "7308",
    gst: 18,
    rate: 220,
    stock: 800,
    unit: "pcs",
  },
  {
    name: "Rebar Threading Machine",
    category: "Machines",
    hsn: "8462",
    gst: 18,
    rate: 135000,
    stock: 25,
    unit: "unit",
  },
  {
    name: "TMT Bar Threading Machine",
    category: "Machines",
    hsn: "8462",
    gst: 18,
    rate: 145000,
    stock: 15,
    unit: "unit",
  },
  {
    name: "Rebar Thread Rolling Machine",
    category: "Machines",
    hsn: "8462",
    gst: 18,
    rate: 155000,
    stock: 10,
    unit: "unit",
  },
  {
    name: "Lanco Die Head Chaser Threading Machine",
    category: "Machines",
    hsn: "8462",
    gst: 18,
    rate: 175000,
    stock: 8,
    unit: "unit",
  },
  {
    name: "Rebar Cold Forging Machine",
    category: "Machines",
    hsn: "8462",
    gst: 18,
    rate: 195000,
    stock: 12,
    unit: "unit",
  },
  {
    name: "Rebar Thread Protection Cap",
    category: "Accessories",
    hsn: "3926",
    gst: 18,
    rate: 5,
    stock: 12000,
    unit: "pcs",
  },
  {
    name: "Rebar Cold Forged Thread Protection Cap",
    category: "Accessories",
    hsn: "3926",
    gst: 18,
    rate: 7,
    stock: 8000,
    unit: "pcs",
  },
  {
    name: "PVC Cover Block",
    category: "Construction Accessories",
    hsn: "3926",
    gst: 18,
    rate: 6,
    stock: 15000,
    unit: "pcs",
  },
  {
    name: "Concrete Plastic Rebar Chair Spacer",
    category: "Construction Accessories",
    hsn: "3926",
    gst: 18,
    rate: 8,
    stock: 10000,
    unit: "pcs",
  },
  {
    name: "Speed Dowel Sleeve",
    category: "Road Construction",
    hsn: "7308",
    gst: 18,
    rate: 65,
    stock: 3000,
    unit: "pcs",
  },
  {
    name: "Concrete Power Trowel Machine",
    category: "Road Construction",
    hsn: "8479",
    gst: 18,
    rate: 85000,
    stock: 10,
    unit: "unit",
  },
  {
    name: "Bull Float",
    category: "Road Construction",
    hsn: "8430",
    gst: 18,
    rate: 25000,
    stock: 15,
    unit: "unit",
  },
  {
    name: "Armour Joint System",
    category: "Flooring",
    hsn: "7308",
    gst: 18,
    rate: 950,
    stock: 500,
    unit: "pcs",
  },
  {
    name: "Formwork Water Stopper",
    category: "Formwork",
    hsn: "7308",
    gst: 18,
    rate: 30,
    stock: 5000,
    unit: "pcs",
  },
  {
    name: "Mivan Formwork Push Pull Jack",
    category: "Formwork",
    hsn: "7308",
    gst: 18,
    rate: 3500,
    stock: 500,
    unit: "pcs",
  },
  {
    name: "Mivan Hole Bari",
    category: "Formwork",
    hsn: "7308",
    gst: 18,
    rate: 120,
    stock: 3000,
    unit: "pcs",
  },
  {
    name: "LDPE Sheets",
    category: "Construction Materials",
    hsn: "3920",
    gst: 18,
    rate: 95,
    stock: 2000,
    unit: "roll",
  },
  {
    name: "EPE Foam Backer Rod",
    category: "Construction Materials",
    hsn: "3921",
    gst: 18,
    rate: 18,
    stock: 5000,
    unit: "meter",
  },
  {
    name: "PQC Texturing Brush",
    category: "Road Construction",
    hsn: "9603",
    gst: 18,
    rate: 1800,
    stock: 150,
    unit: "pcs",
  },
  {
    name: "Anti Smog Gun",
    category: "Safety Equipment",
    hsn: "8424",
    gst: 18,
    rate: 65000,
    stock: 10,
    unit: "unit",
  },
  {
    name: "PVC S Hook Cable",
    category: "Accessories",
    hsn: "8544",
    gst: 18,
    rate: 15,
    stock: 3000,
    unit: "pcs",
  },
  {
    name: "Tie Rod Cone",
    category: "Formwork",
    hsn: "7308",
    gst: 18,
    rate: 12,
    stock: 8000,
    unit: "pcs",
  },
  {
    name: "Expansion Joint",
    category: "Road Construction",
    hsn: "7308",
    gst: 18,
    rate: 450,
    stock: 1000,
    unit: "pcs",
  },
];

async function seedProducts() {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    await Product.deleteMany();

    await Product.insertMany(products);

    console.log("✅ Products Seeded Successfully");
    process.exit();
  } catch (error) {
    console.log(error);
    process.exit(1);
  }
}

seedProducts();